### ISSUE TITLE
Workflow exception handling strategy to send notification upon incident

### ISSUE THREAD

**Issue by wwelling** [TAMULib/mod-camunda#139]
Need to be able to catch exceptions of a task and perform another task to handle. Such as catch exceptions and run a log task or an email task or proceed to next iteration of subprocess.

**Comment by kaladay** [comment]
This REST endpoint may be useful for this: `/history/incident`
https://docs.camunda.org/manual/7.12/reference/rest/history/incident/get-incident-query/

**Comment by kaladay** [comment]
There are several places that could benefit to throwing exceptions when they currently do not (Several of these places the current behavior is just to log the problem).

1. CompressFileDelegate: File operations such as failure to read or write.
2. EmailDelegate: when file attachment does not exist or is not a file.
3. RequestDelegate: Has warnings about type and output problems, need to determine if these are better served as exceptions.
4. FileDelegate: File operations such as failure to read or write.
5. InputDelegate: Has warnings about type and output problems, need to determine if these are better served as exceptions.
6. OutputDelegate: Has warnings about type and output problems, need to determine if these are better served as exceptions.

**Comment by wwelling** [comment]
May consider checking all async before and after to determine "safe points" and relation with exception handling.

**Comment by wwelling** [comment]
Long-running and/or CRON workflows should have email notifications for when complete.
