### ISSUE TITLE
Unable to deactivate workflow when its deployment has an incident

### ISSUE THREAD

**Issue by ghost** [TAMULib/mod-camunda#171]
Should likely be done by clearing the incident and stop the running instance. Not really require deactivating it. However, deactivation is prevented when there is an incident of a running instance.

***NOTE***

This issue has been mitigated by the ability to remove incidents from workflow instances in the camunda dashboard.

**Comment by kaladay** [comment]
This is solved in mod-workflow via: https://github.com/folio-org/mod-workflow/pull/95
