### ISSUE TITLE
Shelflist - holdings exception

### ISSUE THREAD

**Issue by rmathew1011** [TAMULib/mod-camunda#211]
org.camunda.bpm.engine.impl.pvm.PvmException: couldn't execute activity <serviceTask id="database_query_task_1554364a_f73a_41ee_b61b_8c1d8755d021" ...>: /
mnt/workflows/shelflist-holdings/shelflist-holdings-report-1682708949787.csv (No such file or directory)

**Comment by jeremythuff** [comment]
Confirm that this is still occurring

**Comment by jcreel** [comment]
Still occurring - scope the file path to the tenant to fix.

**Comment by jeremythuff** [comment]
This has been resolved
